import { Inter } from "next/font/google";
import "./globals.css";
import Menubar from "@/components/shared/Menubar";
import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dua & Ruqyah | All Duas Collection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-base-200 min-h-screen px-8 py-3">
          <div className="flex gap-4">
            <div className="w-[100px] my-3">
              <Menubar />
            </div>
            <div className="flex-1">
              <Navbar />
              <div className="flex gap-2 w-full">
                <div className="w-4/5">{children}</div>
                <div className="w-1/5">
                  <Sidebar />
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
